### ISSUE TITLE
Update GCC version

### ISSUE THREAD

**Issue by remyabel** [autonomy/toolchain-musl#4]
As mentioned in https://github.com/autonomy/talos/issues/373, GCC 7.4.0 seems to be [missing the -static-pie option](https://gcc.gnu.org/onlinedocs/gcc-7.4.0/gcc/Link-Options.html#Link-Options).

**Comment by andrewrynhard** [comment]
@remyabel Thanks for pointing finding this. I'm going to dig into this some more.

**Comment by andrewrynhard** [comment]
Looks like you forked it. If you already are on it then I can backoff :).

**Comment by remyabel** [comment]
Feel free to take over. I forked it to identify the issue in the first place.

**Comment by andrewrynhard** [comment]
Sounds good 👍.
